services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db
    volumes:
      - ../app:/app/app

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
